package maps

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"roboInsert/models"
)

// func requestMaps(client Clients) (lat, long float64, err error) {
// 	u, _ := url.Parse(apiUrl)

// 	values := url.Values{}
// 	values.Add("address", client.Endereco+""+client.Numero+","+client.Bairro+","+client.Cep+","+client.Pais+","+client.Cidade)
// 	values.Add("key", key)
// 	u.RawQuery = values.Encode()

// 	// Parse(apiUrl + endereco + key) // func Felipe
// 	var rsp *AutoGenerated
// 	// urli := strings.ReplaceAll(apiUrl+endereco+key, " ", "")
// 	req, _ := http.Get(u.String())
// 	json.NewDecoder(req.Body).Decode(&rsp)

// 	if rsp.Status != "OK" || len(rsp.Results) < 1 {
// 		fmt.Println("localização inválida", rsp.Status)
// 		err = fmt.Errorf("google api: %s", rsp.Status)
// 		return
// 	}

// 	lat = rsp.Results[0].Geometry.Location.Lat
// 	long = rsp.Results[0].Geometry.Location.Lng
// 	fmt.Println(values.Encode(), lat, long)
// 	return
// }
// RequestMapsNewclient ...
func RequestMapsNewclient(client models.Client) (lat, long float64) {
	u, _ := url.Parse(apiUrl)

	values := url.Values{}
	values.Add("address", client.Endereco+client.Numero+","+client.Bairro+","+client.Cep+","+client.Cidade+","+client.Pais)
	values.Add("key", key)
	u.RawQuery = values.Encode()

	// Parse(apiUrl + endereco + key) // func Felipe
	var rsp *models.AutoGenerated
	// urli := strings.ReplaceAll(apiUrl+endereco+key, " ", "")
	req, _ := http.Get(u.String())
	json.NewDecoder(req.Body).Decode(&rsp)

	if rsp.Status != "OK" || len(rsp.Results) < 1 {
		fmt.Println("localização inválida", rsp.Status)
		//err = fmt.Errorf("google api: %s", rsp.Status)
		return
	}

	lat = rsp.Results[0].Geometry.Location.Lat
	long = rsp.Results[0].Geometry.Location.Lng
	fmt.Println(values.Encode(), lat, long)
	return
}

const apiUrl = "https://maps.googleapis.com/maps/api/geocode/json"
const key = "AIzaSyDybcJ7PHZPP2es7YN_hd0D5OWjIR3kue0"
